name: Gas Governance & Automation Frequency

on:
  pull_request:
    paths:
      - 'stable-yield-aggregator/**'
      - '.github/workflows/gas-governance.yml'
  push:
    branches: [ main ]

jobs:
  gas-benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install deps
        run: |
          npm install
          cd stable-yield-aggregator && npm install
      - name: Run gas benchmark (current)
        run: |
          cd stable-yield-aggregator
          npx hardhat run scripts/fees-benchmark.js > benchmark-current.log 2>&1 || true
          # Extract gas lines into JSON { label: value }
          node -e "const fs=require('fs');const lines=fs.readFileSync('benchmark-current.log','utf8').split(/\n/);const out={};for(const l of lines){const m=l.match(/^(.*) gasUsed= (\d+)/);if(m){out[m[1].trim()]=Number(m[2]);}}fs.writeFileSync('benchmark-current.json',JSON.stringify(out,null,2));"
          cat benchmark-current.json
      - name: Download baseline artifact (if exists)
        uses: actions/download-artifact@v4
        with:
          name: gas-benchmark-baseline
        continue-on-error: true
      - name: Compare with baseline
        run: |
          cd stable-yield-aggregator
          if [ -f benchmark-baseline.json ] && [ -f benchmark-current.json ]; then
            node scripts/fees-benchmark-compare.js --baseline benchmark-baseline.json --current benchmark-current.json --threshold 5;
          else
            echo "Baseline or current benchmark missing; skipping comparison";
          fi
      - name: Upload current benchmark as artifact
        uses: actions/upload-artifact@v4
        with:
          name: gas-benchmark-current
          path: stable-yield-aggregator/benchmark-current.json
  update-baseline:
    needs: gas-benchmark
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install deps
        run: |
          npm install
          cd stable-yield-aggregator && npm install
      - name: Run gas benchmark (baseline refresh)
        run: |
          cd stable-yield-aggregator
          npx hardhat run scripts/fees-benchmark.js > benchmark-baseline.log 2>&1 || true
          node -e "const fs=require('fs');const lines=fs.readFileSync('benchmark-baseline.log','utf8').split(/\n/);const out={};for(const l of lines){const m=l.match(/^(.*) gasUsed= (\d+)/);if(m){out[m[1].trim()]=Number(m[2]);}}fs.writeFileSync('benchmark-baseline.json',JSON.stringify(out,null,2));"
      - name: Publish baseline artifact
        uses: actions/upload-artifact@v4
        with:
          name: gas-benchmark-baseline
          path: stable-yield-aggregator/benchmark-baseline.json
  frequency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate rebalance frequency placeholder
        run: |
          echo "Rebalance frequency check placeholder (implement keeper logs ingestion later)." 
